sudo: false
language: cpp

linux_gcc: &linux_gcc
  os: linux
  dist: xenial
  compiler: gcc
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:mhier/libboost-latest'
      packages:
        - g++-5
        - libgtest-dev
        - boost1.74

linux_clang: &linux_clang
  os: linux
  dist: xenial
  compiler: clang
  addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-trusty-4.0
        - sourceline: 'ppa:mhier/libboost-latest'
      packages:
        - clang-4.0
        - libgtest-dev
        - boost1.74

matrix:
  include:
  - <<: *linux_gcc
    env:
      - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && CONFIG=Debug && SHARED=False"

  - <<: *linux_gcc
    env:
      - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && CONFIG=Debug && SHARED=True"

  - <<: *linux_gcc
    env:
      - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && CONFIG=Release && SHARED=False"

  - <<: *linux_gcc
    env:
      - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && CONFIG=Release && SHARED=True"

  - <<: *linux_gcc
    env:
      - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && CONFIG=Debug && SHARED=False && SANITIZE=address"

  - <<: *linux_gcc
    env:
      - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5 && CONFIG=Debug && SHARED=False && COVERAGE=True"

  - <<: *linux_clang
    env:
     - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0 && CONFIG=Debug && SHARED=False"

  - <<: *linux_clang
    env:
     - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0 && CONFIG=Debug && SHARED=True"

  - <<: *linux_clang
    env:
     - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0 && CONFIG=Release && SHARED=False"

  - <<: *linux_clang
    env:
     - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0 && CONFIG=Release && SHARED=False"

cache:
  - apt: true
  - directories:
    - $HOME/lcov
    - $HOME/gtest
    - $HOME/gsl-lite

before_install:
# Set up CC/CXX variables.
  - eval "${MATRIX_EVAL}"
  - export CMAKE=cmake
  - export COVERAGE=${COVERAGE:-False}
  - export SANITIZE=${SANITIZE:-off}
# workaround for not having lcov 1.13
  - if [ ! -d "lcov/usr/bin/lcov" ]; then
      wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz;
      tar -xzf lcov_1.13.orig.tar.gz;
      mkdir lcov || true;
      DESTDIR=$HOME/lcov make -C lcov-1.13/ install;
    fi
  - export LCOV=$HOME/lcov/usr/local/bin/lcov

# workaround for gtest not providing its own libraries (sigh)
  - if [ ! -d "gtest/libgtest.a" ]; then
      mkdir gtest || true;
      cd gtest;
      $CMAKE /usr/src/gtest -DCMAKE_CXX_FLAGS='-fPIC' && make;
      cd ..;
    fi
  - export GTEST_ROOT=$PWD/gtest

# install gsl-lite
  - if [ ! -d "gsl-lite/include/gsl/gsl-lite.hpp" ]; then
      wget https://github.com/gsl-lite/gsl-lite/archive/v0.34.0.tar.gz;
      tar -xzf v0.34.0.tar.gz;
      mkdir gsl-lite || true;
      cd gsl-lite-0.34.0;
      $CMAKE -DCMAKE_INSTALL_PREFIX=$HOME/gsl-lite .;
      make -j2 && make install;
      cd ..;
    fi
  - export GSLLITE_ROOT=$PWD/gsl-lite

before_script:
  - mkdir build || true
  - cd build
  - $CMAKE -DCMAKE_BUILD_TYPE=$CONFIG -DBUILD_SHARED_LIBS=$SHARED -DTELNETPP_SANITIZE=$SANITIZE -DTELNETPP_COVERAGE=$COVERAGE -Dgsl-lite_DIR=$GSLLITE_ROOT/lib/cmake/gsl-lite ..

script:
  - make VERBOSE=1
  - if [ "$COVERAGE" == "True" ]; then
        $LCOV --gcov-tool=gcov-5 --base-directory . --directory . --zerocounters -q;
    fi
  - make test

after_failure:
  - cat Testing/Temporary/LastTest.log

after_success:
  - if [ "$COVERAGE" == "True" ]; then
        $LCOV --gcov-tool=gcov-5 --base-directory . --directory .  --capture --output-file coverage.info;
        $LCOV --gcov-tool=gcov-5 --remove coverage.info '*/test/*' '/usr/*' '*/.conan/*' --output-file coverage.info;
        $LCOV --gcov-tool=gcov-5 --list coverage.info;
        coveralls-lcov --repo-token ${COVERALLS_TOKEN} coverage.info;
    fi

notifications:
  email:
    on_success: change # [always|never|change] # default: change
    on_failure: change # [always|never|change] # default: always
  slack:
    rooms:
      - kazdragon:E8B4Cs4p3TiVLqHAq8wYYTr3#ci
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/dd988061905795003d31
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

