name: coverage

on: 
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - build_type: Release

    env:
      EXTERNAL_ROOT: /home/runner/3party
      BUILD_TYPE: ${{ matrix.build_type }}

    steps:
    - uses: actions/checkout@v2

    - name: Add Boost repository
      shell: bash
      run: sudo apt-add-repository ppa:mhier/libboost-latest
    
    - name: Install latest Boost
      shell: bash
      run: sudo apt install boost1.74

    - name: Install Coverage reporting software
      shell: bash
      run: sudo gem install coveralls-lcov
        
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch


    # Build a cache for LCOV.
    - name: Cache lcov
      uses: actions/cache@v2
      with:
        path: ~/.lcov
        key: lcov-cache-${{ steps.extract_branch.outputs.branch }}
        restore-keys: |
          lcov-cache-master

    - name: Install LCOV
      shell: bash
      run: |
        if [ ! -f "$HOME/.lcov/local/bin/lcov" ]; then
          mkdir $HOME/.lcov-build || true;
          cd $HOME/.lcov-build;
          wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz;
          tar -xzf lcov_1.13.orig.tar.gz;
          mkdir -p $HOME/.lcov || true;
          DESTDIR=$HOME/.lcov make -C lcov-1.13/ install;
        fi
        echo "##[set-output name=bin;]$(echo $HOME/.lcov/usr/local/bin/lcov)"
      id: lcov

    - name: Install dependencies from source
      run: .ci/fetch_system_dependencies.sh
      
    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_PREFIX_PATH=$EXTERNAL_ROOT -DTELNETPP_WITH_ZLIB=True -DTELNETPP_COVERAGE=True

    - name: Build
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config $BUILD_TYPE

    - name: Zero test counters
      shell: bash
      run: ${{ steps.lcov.outputs.bin }} --gcov-tool=gcov-7 --base-directory ${{runner.workspace}}/build --directory ${{runner.workspace}}/build --zerocounters -q

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -C $BUILD_TYPE

    - name: Calculate coverage
      shell: bash
      run: |
        ${{ steps.lcov.outputs.bin }} --gcov-tool=gcov-7 --base-directory ${{runner.workspace}}/build --directory ${{runner.workspace}}/build  --capture --output-file coverage.info;
        ${{ steps.lcov.outputs.bin }} --gcov-tool=gcov-7 --remove coverage.info '*/test/*' '/usr/*' '*/3party/*' --output-file coverage.info;
        ${{ steps.lcov.outputs.bin }} --gcov-tool=gcov-7 --list coverage.info;
        coveralls-lcov --repo-token ${{ secrets.github_token }} coverage.info;
